//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.14 at 11:29:13 AM WAT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.soap.io/example", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package io.soap.example;
